# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            cuevano.ca
tagline:          'by Jorge Aranda'
description:      'Jorge Aranda&#039;s personal website'
url:              http://cuevano.ca

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

gems:
  - jekyll-paginate
  - redcarpet
