# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Cuevano
tagline:          '~ Jorge Aranda'
description:      'Jorge Aranda&#039;s personal website'
url:              http://cuevano.ca

author:
  name:           'Jorge Aranda '
  url:            https://cuevano.ca

paginate:         5

gems:
  - jekyll-paginate
  - redcarpet

exclude:
  - s3_website.yml
